#!/usr/bin/env bash
curl -OL https://github.com/CxxTest/cxxtest/releases/download/4.4/cxxtest-4.4.tar.gz > cxxtest-4.4.tar.gz
tar xpvzf cxxtest-4.4.tar.gz > /dev/null
chmod 755 cxxtest-4.4/bin/cxxtestgen
rm cxxtest-4.4.tar.gz
